var data = [
  {
    "AGENT CODE": "ADH",
    "AGENT FIRST AND LAST NAME": "Danielle Hoffmann",
    "REAL ESTATE TITLE": "Real Estate Broker",
    "AGENT NEST REALTY EMAIL": "danielle.hoffmann@nestrealty.com",
    "AGENT PHONE NUMBER": "828-435-2520",
    "CLIENT NAME": "Fay Broadbent",
    "CLIENT ADDRESS": "6088 Little River Court",
    "CLIENT CITY": "Granite Falls",
    "CLIENT STATE": "NC",
    "CLIENT ZIP": "28630",
    "EMAIL 1 (IF DESIRED)": "",
    "EMAIL 2 (IF DESIRED)": "",
    "MAP CUSTOMIZATION": "Fay's"
  },
  {
    "AGENT CODE": "ADH",
    "AGENT FIRST AND LAST NAME": "Danielle Hoffmann",
    "REAL ESTATE TITLE": "Real Estate Broker",
    "AGENT NEST REALTY EMAIL": "danielle.hoffmann@nestrealty.com",
    "AGENT PHONE NUMBER": "828-435-2520",
    "CLIENT NAME": "Susan and David Stagg",
    "CLIENT ADDRESS": "300 Pinnacle Peak Lane",
    "CLIENT CITY": "Flat Rock",
    "CLIENT STATE": "NC",
    "CLIENT ZIP": "28731",
    "EMAIL 1 (IF DESIRED)": "susanannstagg@gmail.com",
    "EMAIL 2 (IF DESIRED)": "davidastagg@gmail.com",
    "MAP CUSTOMIZATION": "Sue and Dave's"
  },
  {
    "AGENT CODE": "ADH",
    "AGENT FIRST AND LAST NAME": "Danielle Hoffmann",
    "REAL ESTATE TITLE": "Real Estate Broker",
    "AGENT NEST REALTY EMAIL": "danielle.hoffmann@nestrealty.com",
    "AGENT PHONE NUMBER": "828-435-2520",
    "CLIENT NAME": "Chris and Shelley Bean",
    "CLIENT ADDRESS": "2201 Harden Circle",
    "CLIENT CITY": "Hendersonville",
    "CLIENT STATE": "NC",
    "CLIENT ZIP": "28792",
    "EMAIL 1 (IF DESIRED)": "shelbean57@gmail.com",
    "EMAIL 2 (IF DESIRED)": "",
    "MAP CUSTOMIZATION": "The Beans's"
  },
  {
    "AGENT CODE": "ADH",
    "AGENT FIRST AND LAST NAME": "Danielle Hoffmann",
    "REAL ESTATE TITLE": "Real Estate Broker",
    "AGENT NEST REALTY EMAIL": "danielle.hoffmann@nestrealty.com",
    "AGENT PHONE NUMBER": "828-435-2520",
    "CLIENT NAME": "Fred and Marilyn Broadbent",
    "CLIENT ADDRESS": "22 Thistlewood lane",
    "CLIENT CITY": "Hendersonville",
    "CLIENT STATE": "NC",
    "CLIENT ZIP": "28791",
    "EMAIL 1 (IF DESIRED)": "",
    "EMAIL 2 (IF DESIRED)": "",
    "MAP CUSTOMIZATION": "The Broadbent's"
  },
  {
    "AGENT CODE": "ADH",
    "AGENT FIRST AND LAST NAME": "Danielle Hoffmann",
    "REAL ESTATE TITLE": "Real Estate Broker",
    "AGENT NEST REALTY EMAIL": "danielle.hoffmann@nestrealty.com",
    "AGENT PHONE NUMBER": "828-435-2520",
    "CLIENT NAME": "Barry and Sharon Borakove",
    "CLIENT ADDRESS": "273 Towne Place Dr",
    "CLIENT CITY": "Hendersonville",
    "CLIENT STATE": "NC",
    "CLIENT ZIP": "28792",
    "EMAIL 1 (IF DESIRED)": "",
    "EMAIL 2 (IF DESIRED)": "",
    "MAP CUSTOMIZATION": "The Borakove's"
  },
  {
    "AGENT CODE": "ADH",
    "AGENT FIRST AND LAST NAME": "Danielle Hoffmann",
    "REAL ESTATE TITLE": "Real Estate Broker",
    "AGENT NEST REALTY EMAIL": "danielle.hoffmann@nestrealty.com",
    "AGENT PHONE NUMBER": "828-435-2520",
    "CLIENT NAME": "Denise and Glan Evans",
    "CLIENT ADDRESS": "107 Mountain Place",
    "CLIENT CITY": "Hendersonville",
    "CLIENT STATE": "NC",
    "CLIENT ZIP": "28791",
    "EMAIL 1 (IF DESIRED)": "",
    "EMAIL 2 (IF DESIRED)": "",
    "MAP CUSTOMIZATION": "The Evans's"
  },
  {
    "AGENT CODE": "ADH",
    "AGENT FIRST AND LAST NAME": "Danielle Hoffmann",
    "REAL ESTATE TITLE": "Real Estate Broker",
    "AGENT NEST REALTY EMAIL": "danielle.hoffmann@nestrealty.com",
    "AGENT PHONE NUMBER": "828-435-2520",
    "CLIENT NAME": "Judy and Peter Walgate",
    "CLIENT ADDRESS": "208 Camelia Way",
    "CLIENT CITY": "Hendersonville",
    "CLIENT STATE": "NC",
    "CLIENT ZIP": "28739",
    "EMAIL 1 (IF DESIRED)": "",
    "EMAIL 2 (IF DESIRED)": "",
    "MAP CUSTOMIZATION": "The Walgate's"
  },
  {
    "AGENT CODE": "ADH",
    "AGENT FIRST AND LAST NAME": "Danielle Hoffmann",
    "REAL ESTATE TITLE": "Real Estate Broker",
    "AGENT NEST REALTY EMAIL": "danielle.hoffmann@nestrealty.com",
    "AGENT PHONE NUMBER": "828-435-2520",
    "CLIENT NAME": "Wade Facey",
    "CLIENT ADDRESS": "212 DeerPath Lane",
    "CLIENT CITY": "Hendersonville",
    "CLIENT STATE": "NC",
    "CLIENT ZIP": "28739",
    "EMAIL 1 (IF DESIRED)": "",
    "EMAIL 2 (IF DESIRED)": "",
    "MAP CUSTOMIZATION": "Wade's"
  },
  {
    "AGENT CODE": "ADH",
    "AGENT FIRST AND LAST NAME": "Danielle Hoffmann",
    "REAL ESTATE TITLE": "Real Estate Broker",
    "AGENT NEST REALTY EMAIL": "danielle.hoffmann@nestrealty.com",
    "AGENT PHONE NUMBER": "828-435-2520",
    "CLIENT NAME": "Jim and Kitty Olsen",
    "CLIENT ADDRESS": "103 Beckwood Court",
    "CLIENT CITY": "Flat Rock",
    "CLIENT STATE": "NC",
    "CLIENT ZIP": "28731",
    "EMAIL 1 (IF DESIRED)": "",
    "EMAIL 2 (IF DESIRED)": "",
    "MAP CUSTOMIZATION": "The Olsen's"
  },
  {
    "AGENT CODE": "ADH",
    "AGENT FIRST AND LAST NAME": "Danielle Hoffmann",
    "REAL ESTATE TITLE": "Real Estate Broker",
    "AGENT NEST REALTY EMAIL": "danielle.hoffmann@nestrealty.com",
    "AGENT PHONE NUMBER": "828-435-2520",
    "CLIENT NAME": "John and Tracy Payne",
    "CLIENT ADDRESS": "123 Clover Hollow Lane",
    "CLIENT CITY": "Penrose",
    "CLIENT STATE": "NC",
    "CLIENT ZIP": "28766",
    "EMAIL 1 (IF DESIRED)": "",
    "EMAIL 2 (IF DESIRED)": "",
    "MAP CUSTOMIZATION": "The Payne's"
  }
]
